### ISSUE TITLE
missing file on category info

### ISSUE THREAD

**Issue by Solacex** [clin1223/VLDet#5]
Thanks for your inspiring work!

It seems that some file is missing:  'datasets/coco/zero-shot/instances_train2017_seen_2_del_cat_info.json'  at https://github.com/clin1223/VLDet/blob/c3b9bc52205cd1c48b5b8a43212ee04260f92897/configs/VLDet_OVCOCO_CLIP_R50_1x_caption.yaml#L19 

Would you mind offering this file or script to generate it？

**Comment by clin1223** [comment]
Hi,
you can generate it by 

python tools/get_lvis_cat_info.py --ann datasets/coco/zero-shot/instances_train2017_seen_2_del.json

Thanks!
--Chuang

**Comment by kinredon** [comment]
@clin1223 Hi, where can I get "datasets/coco/zero-shot/instances_train2017_seen_2_del.json"?
