### ISSUE TITLE
Can not get the dataset.

### ISSUE THREAD

**Issue by JiuqingDong** [clin1223/VLDet#6]
You suggest following [OVR-CNN](https://github.com/alirezazareian/ovr-cnn/blob/master/ipynb/003.ipynb) to create the open-vocabulary COCO split.
However, I cam not got 
coco/
    zero-shot/
        instances_train2017_seen_2.json
        instances_val2017_all_2.json

Besides,  I didn't see 'coco_65_concepts.txt' in your Google driver.

Could you provide these files? Thank you very much.

**Comment by clin1223** [comment]
Hi,

Sorry, can you provide the error information when you generate json file following https://github.com/alirezazareian/ovr-cnn/blob/master/ipynb/003.ipynb

 'coco_65_concepts.txt' is not necessary for running the code.

Thanks!

--Chuang

**Comment by JiuqingDong** [comment]
I transfer .ipynb to .py and run the code, and this is the output. I can not find the reasons.

multiai3@multiai3:~/Jiuqing/ovr$ python 003.py 
49 17
giraffe not found
handbag not found
frisbee not found
skis not found
snowboard not found
skateboard not found
surfboard not found
broccoli not found
donut not found
toaster not found
toothbrush not found
False
Traceback (most recent call last):
  File "003.py", line 62, in <module>
    mask = (1 - encoded_class_list['special_tokens_mask']).to(torch.float32)
KeyError: 'special_tokens_mask'

**Comment by QiueY514** [comment]
> Hi,
> 
> Sorry, can you provide the error information when you generate json file following https://github.com/alirezazareian/ovr-cnn/blob/master/ipynb/003.ipynb
> 
> 'coco_65_concepts.txt' is not necessary for running the code.
> 
> Thanks!
> 
> --Chuang

Hi! Could you release the files `instances_train2017_seen_2.json` and `instances_val2017_all_2.json`? There is something wrong when I try to generate these files.
